

name: armTemplateDeployment
on:
  push: 
    branches: 
      - main
  workflow_dispatch:
jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy resource group with AZ CLI
        uses: Azure/cli@v2.0.0
        with:
          inlineScript: |
            az deployment sub create --location "westeurope" --template-file ./arm/resourcegroup.json
