

name: armTemplateDeployment
on:
  push: 
    branches: 
      - main
  workflow_dispatch:
jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy Resource Group
        id: deployResurceGroup
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          template: ./arm/resourcegroup.json
          subscriptionId: 3e4e586a-a0ff-49db-bb07-e8cb8fa5601a
          parameters: ./arm/resourcegroup.parameters.json
          region: westeurope

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          template: ./arm/storageaccount.json
          parameters: ./arm/storageaccount.parameter.json
          subscriptionId: 3e4e586a-a0ff-49db-bb07-e8cb8fa5601a
          resourceGroupName: ${{steps.deployResurceGroup.outputs.resourceGroupName}}
          